### ISSUE TITLE
capture.output() requires user to resolve all conflicts before advancing

### ISSUE THREAD

**Issue by salauer** [r-lib/conflicted#44] opened 2019-07-19 20:51 UTC
I'm not sure whose issue this is, but I noticed that code that had capture.output() from utils running inside it asked me to resolve conflicts that were unrelated to the function call before allowing the code to run. I noticed it when using the brms package in tandem with tidyverse:

``` r
library(conflicted)
library(tidyverse)
library(brms)
#> Loading required package: Rcpp
#> Loading 'brms' package (version 2.9.0). Useful instructions
#> can be found by typing help('brms'). A more detailed introduction
#> to the package is available through vignette('brms_overview').
conflict_scout()
#> 10 conflicts:
#> * `.DollarNames`: [Rcpp]
#> * `filter`      : dplyr, stats
#> * `formals<-`   : [Rcpp]
#> * `intersect`   : [dplyr]
#> * `lag`         : dplyr, stats
#> * `Position`    : ggplot2, base
#> * `prompt`      : [Rcpp]
#> * `setdiff`     : [dplyr]
#> * `setequal`    : [dplyr]
#> * `union`       : [dplyr]

tmp_df <- tibble(Y=rnorm(100),
                 X=rnorm(100))

brm_fit <- brm(Y~s(X,bs='cr'),
               chains=1,iter=1000,
               family="gaussian", data=tmp_df)
#> Compiling the C++ model
#> [conflicted] `filter` found in 2 packages.
#> Either pick the one you want with `::` 
#> * dplyr::filter
#> * stats::filter
#> Or declare a preference with `conflict_prefer()`
#> * conflict_prefer("filter", "dplyr")
#> * conflict_prefer("filter", "stats")
```

When I resolved that conflict, it went to the next one on the list:

``` r
library(conflicted)
library(tidyverse)
library(brms)
#> Loading required package: Rcpp
#> Loading 'brms' package (version 2.9.0). Useful instructions
#> can be found by typing help('brms'). A more detailed introduction
#> to the package is available through vignette('brms_overview').
# conflict_scout()
conflict_prefer("filter", "stats")
#> [conflicted] Will prefer stats::filter over any other package

tmp_df <- tibble(Y=rnorm(100),
                 X=rnorm(100))

brm_fit <- brm(Y~s(X,bs='cr'),
               chains=1,iter=1000,
               family="gaussian", data=tmp_df)
#> Compiling the C++ model
#> [conflicted] `lag` found in 2 packages.
#> Either pick the one you want with `::` 
#> * dplyr::lag
#> * stats::lag
#> Or declare a preference with `conflict_prefer()`
#> * conflict_prefer("lag", "dplyr")
#> * conflict_prefer("lag", "stats")
```

And so on, until all conflicts were resolved. By using debug(), I found that this problem appears to originate in the capture.output() function, but it doesn't use filter(), lag(), or any of the other conflicted functions to run. My full script had 20+ conflicts that don't usually pertain to my code, so it was a bit annoying to work through, though not intractable. I figured I'd bring it to your attention.

<sup>Created on 2019-07-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment] 2021-11-16 14:15
When I run this code, I get the following backtrace:

```
Backtrace:
     █
  1. ├─brms::brm(...)
  2. │ └─brms::do_call(compile_model, compile_args)
  3. │   └─brms:::eval2(call, envir = args, enclos = envir)
  4. │     └─base::eval(expr, envir, ...)
  5. │       └─base::eval(expr, envir, ...)
  6. │         └─brms:::.fun(...)
  7. │           └─brms:::.compile_model(model, ...)
  8. │             ├─brms:::eval_silent(...)
  9. │             │ └─base::eval(expr, envir)
 10. │             │   └─base::eval(expr, envir)
 11. │             └─brms::do_call(rstan::stan_model, args)
 ```

So I don't think this has anything to do with `capture.output()`, but is instead something to do with how rstan works, i.e. this is a duplicate of #53.

**Closed by hadley** 2021-11-16 14:15 UTC
