### ISSUE TITLE
Conflicted breaks other packages

### ISSUE THREAD

**Issue by mike-lawrence** [r-lib/conflicted#11] opened 2018-06-11 01:11 UTC
Is it intentional that conflicted outright breaks other packages? I thought it was intended to help enforce explicit namespace behaviour on the part of the user, but it seems to also expect this of the packages used by the user. For example, when I run:

    library("conflicted")
    library("rstan")
    stancode <- 'data {real y_mean;} parameters {real y;} model {y ~ normal(y_mean,1);}'
    mod <- rstan::stan_model(model_code = stancode)

I get: 

    Error: plot found in 2 packages. You must indicate which one you want with ::
    * rstan::plot
     * graphics::plot

Presumably because rstan::stan_model internally uses `plot` without explicit namespace reference. But surely the internals of a package is not something one can expect users to be able to fix?

**Comment by lionel-** [comment] 2018-06-11 03:18
Reprex:

```r
library("conflicted")
library("rstan")

exists("plot", mode = "S4")
```

**Comment by hadley** [comment] 2018-06-11 13:36
I think this is a duplicate of #8 (because we need to handle how S4 shadows functions with generics)

**Closed** 2018-07-24 18:45 UTC
