### ISSUE TITLE
R session terminates with conflicted and GEOquery (Bioconductor package)

### ISSUE THREAD

**Issue by sraorao** [r-lib/conflicted#8] opened 2018-06-05 15:01 UTC
When a function in GEOquery Bioconductor package is run after loading the conflicted package, R session terminates. As I couldn't see any error messages before R terminated in Rstudio, I ran the same lines at the command line. 

```
> library(conflicted)
> library(GEOquery)
Loading required package: Biobase
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, cbind, colMeans, colnames,
    colSums, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
    grepl, intersect, is.unsorted, lapply, lengths, Map, mapply, match,
    mget, order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rowMeans, rownames, rowSums, sapply, setdiff, sort,
    table, tapply, union, unique, unsplit, which, which.max, which.min

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.

Setting options('download.file.method.GEOquery'='auto')
Setting options('GEOquery.inmemory.gpl'=FALSE)
> gset <- getGEO("GSE39549", GSEMatrix =TRUE, AnnotGPL=FALSE, destdir = ".")
terminate called after throwing an instance of 'Rcpp::eval_error'
  what():  Evaluation error: evalq found in 2 packages. You must indicate which one you want with ::
 * BiocGenerics::evalq
 * base::evalq.
Aborted (core dumped)
```
Session info after loading the packages but before running getGEO()

```
> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.4 LTS

Matrix products: default
BLAS: /usr/lib/atlas-base/atlas/libblas.so.3.0
LAPACK: /usr/lib/atlas-base/atlas/liblapack.so.3.0

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
[1] GEOquery_2.46.15    Biobase_2.38.0      BiocGenerics_0.24.0
[4] conflicted_0.1.0   

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.17     tidyr_0.8.1      crayon_1.3.4     dplyr_0.7.5     
 [5] assertthat_0.2.0 R6_2.2.2         magrittr_1.5     pillar_1.2.2    
 [9] rlang_0.2.0.9001 bindrcpp_0.2.2   limma_3.34.9     xml2_1.2.0      
[13] readr_1.1.1      glue_1.2.0       purrr_0.2.4      hms_0.4.2       
[17] compiler_3.4.4   pkgconfig_2.0.1  tidyselect_0.2.4 bindr_0.1.1     
[21] tibble_1.4.2    

```

**Comment by hadley** [comment] 2018-06-05 15:10
This looks like a problem with the GEOquery package - it's depending on a bunch of packages and not managing it's own imports correctly.

**Comment by sraorao** [comment] 2018-06-05 17:12
Ah okay, thanks. I thought conflicted would be a great package for a lot of functions in Bioconductor, but it looks like it's not so simple!

**Comment by hadley** [comment] 2018-06-05 17:32
Oh looking into this more, the "problem" is that is actually that BiocGenerics overrides base functions (presumably to provide S4 dispatch). If @mtmorgan is interested, we could figure out a general strategy to resolve this.

**Comment by mtmorgan** [comment] 2018-06-05 18:14
Definitely interested; usually / always BiocGenerics 'does the right thing' in that the default is to dispatch to base.

**Comment by hpages** [comment] 2018-06-05 18:40
Yes, promoting an exiting non-S4 function to S4 is always going to mask the original function. But this is normal and shouldn't be seen as a conflict. Note that it can happen between 2 arbitrary packages B and A, not just between B and base. B will typically depend or import A. Thanks!

**Comment by hadley** [comment] 2018-06-05 19:05
Hmmm I wonder if I can handle this in general for S4 generics. What's the best way to tell if an S4 generic has been created from an existing function?

**Comment by mtmorgan** [comment] 2018-06-05 19:17
(not answering the question, but...) it seems like a problem that the error aborts Rcpp; shouldn't it just throw the error and return to the console?

Also, since (and I haven't got through this) being loaded but not attached
```
library(conflicted)
gset <- GEOquery::getGEO("GSE39549", GSEMatrix =TRUE, AnnotGPL=FALSE, destdir = ".")
...
>
```
'works', it seems like Rcpp is evaluating something (looking up `evalq()`?) on the search path instead of in the base environment?

**Comment by hpages** [comment] 2018-06-05 19:36
Not sure this is the best way to tell if an S4 generic has been created from an existing function, but Ione way is to look at the default method i.e. at the method for signature `"ANY"`. When promoted to an S4 generic, the original function is automatically made the default method for the new generic:
```
> toto <- function(x, y) NULL

> setGeneric("toto")
[1] "toto"

> showMethods("toto")
Function: toto (package .GlobalEnv)
x="ANY"

> selectMethod("toto", "ANY")
Method Definition (Class "derivedDefaultMethod"):
function (x, y) 
NULL

Signatures:
        x    
target  "ANY"
defined "ANY"
```
Unlike other user-created methods, this default method is an object of class derivedDefaultMethod:
```
> setMethod("toto", c("vector", "vector"), function(x, y) NULL)

> showMethods("toto")
Function: toto (package .GlobalEnv)
x="ANY", y="ANY"
x="vector", y="vector"

> class(selectMethod("toto", "ANY"))
[1] "derivedDefaultMethod"
attr(,"package")
[1] "methods"

> class(selectMethod("toto", c("vector", "vector")))
[1] "MethodDefinition"
attr(,"package")
[1] "methods"
```
So the test would be something like `is(selectMethod(toto, "ANY"), "derivedDefaultMethod")`.

Hope this helps.

**Comment by hadley** [comment] 2018-06-06 00:33
@mtmorgan I assume that it's because conflicted causes an error to be thrown in an unanticipated place in Rcpp code; it's probably worth looking into, but I don't have the time to do it (and it seems like we should be able to resolve some other way)

@hpages perfect thanks!

For the `evalq()` case, how would you feel about adding some attribute to `BiocGenerics::evalq()` that explicitly flags it as a superset of `base::evalq()`? (I can totally understand being resistant to the idea of adding some feature just to help out conflicted, but it seems like useful metadata that we might be able to use in other ways)

**Comment by hpages** [comment] 2018-06-06 01:17
When B depends on (or imports) A and B exports a symbol that masks a symbol already exported by A, shouldn't conflicted assume that the masking is intended so not see it as a conflict? Promotion to S4 generic and the replacement of `base::evalq()` with `BiocGenerics::evalq()` are both particular cases of this more general situation.

**Comment by hpages** [comment] 2018-06-06 15:14
Note that when you mask a function defined in a package that you **explicitly** depend on, you can hardly miss that because R tells you at load time. So it's fair to assume that the masking is intentional and not accidental. If conflicted uses this criteria to decide that the masking is not a conflict and the masking is accidental, then it will be a false negative. The question is: what is more acceptable, a few false negatives or a few false positives?

**Comment by hadley** [comment] 2018-06-06 15:52
What do you mean by "explicitly depend" on?

**Comment by hpages** [comment] 2018-06-06 16:35
I mean _direct_ dependency (i.e. A is listed in Depends and/or Imports) as opposed to _indirect_ dependency (where B depends on A via a cascade of deps). In the case of direct dependency, there is an explicit intention from B's author to depend on A. It's not that B gets loaded after A by chance.

**Comment by hadley** [comment] 2018-06-06 18:05
If I only import a handful of functions from another package, I might not be aware that I'm also providing a function with the same name as that package?

**Comment by hpages** [comment] 2018-06-06 20:08
Actually forget the "redefine" part in "when package B redefine and exports a symbol that it imports". Some packages import a symbol to just export it without redefining it (I never quite understood why they would do that). So the criteria would just be: masking is considered intentional when package B exports a symbol that it imports. This still covers promotion to S4 generic and the `evalq` case but now it also covers the direct in-and-out situation. (It seems that conflicted is already handling the direct in-and-out situation properly though.)

**Comment by hadley** [comment] 2018-06-06 20:18
I think I'm missing something, because I don't see how it covers the `evalq()` case — `evalq()` is never explicit imported from base.

**Comment by hpages** [comment] 2018-06-06 20:32
I didn't use "explicitly" in the formulation of the criteria. BiocGenerics imports `evalq` from base (not explicitly) and exports it so `evalq` satisfies the criteria.

**Comment by hadley** [comment] 2018-06-06 20:36
In that case I'm not sure that the criteria is very useful because dplyr implicitly imports both filter and lag from stats, and overrides them with different behaviour. I don't think you can read much in to an implicit import.

**Comment by hpages** [comment] 2018-06-06 20:53
I didn't know dplyr was doing this. This kind of intentional masking is a no-no in Bioconductor. Intentional masking is considered ok only when it **extends** the original behavior, not when it replaces it with a different behavior. By extend I mean that the new function supports more input i.e. input where the old function would have failed. But it should still work on any input for which the original function worked and return exactly the same thing. I think that's what you called the new function being a "superset" of the function it replaces earlier in this issue. Promotion to S4 generic and the `evalq` use case fall in this category. Any other intentional function masking in Bioconductor is expected to fall in this category. I naively took for granted that people would only do this kind of superset replacement. 

So maybe add an attribute to `filter()` and `lag()` to explicitly flag them as not providing a superset of what they override?

**Comment by hadley** [comment] 2018-06-06 20:59
I think our discussion has come down to an empirical question: do most people obey the superset principle (and hence we should label the exception with `superset = FALSE`, or do most people fail to obey it (in which case it's less effort to label the exceptions with `superset = TRUE`).

Given that I only just learned about this principle, I'm learning towards the second option 😉

**Comment by hpages** [comment] 2018-06-06 21:27
It's a philosophical question:

Shouldn't people be considered innocent unless proved guilty?

My feeling it that most people obey the superset principle. And if I'm wrong, good citizens shouldn't be forced to wear a tag that they are good citizens anyway :wink: 

More seriously, and from a purely practical point of view, going for the 1st option makes it a tidyverse business only i.e. we don't need to change anything in Bioconductor.

**Comment by hadley** [comment] 2018-06-06 21:49
Clearly you are an optimist, and I am a pessimist :smile:

But yes, this is more clearly my problem now, not bioconductor's. Thanks for the illuminating discussion! 

(I'd also love to hear if you think conflicted is at all useful within bioconductor - I suspect the chances of unintended conflicts between packages is much smaller due to the smaller surface area and greater centralisation)

**Comment by mtmorgan** [comment] 2018-06-06 22:00
FWIW -- once one gets past the segfault in the original comment of this issue (by installing Kevin's Rcpp branch https://github.com/RcppCore/Rcpp/tree/bugfix/rcpp-eval-base-symbols and re-installing all Rcpp-dependent packages used by GEOquery) one gets

```
Error: sort found in 2 packages. You must indicate which one you want with ::
 * BiocGenerics::sort
 * base::sort
```

Where the problem is actually from dplyr's C++ code

```
Thread 1 "R" hit Breakpoint 2, dplyr::CharacterVectorOrderer::CharacterVectorOrderer (this=0x7ffffffd7280, data=...) at api.cpp:123
123	  CharacterVector s_uniques = Language("sort", uniques).fast_eval();
```

Using `Language()` in this way means that `sort` is found on the search path, rather than in / via the dplyr namespace or explicitly though a call that is the equivalent of `base::sort` (there is also a call to `unique` in the dplyr code). The solution might be to arrange for the call to be evaluated in the package namespace, or to explicitly discover base::sort along the lines of https://github.com/RcppCore/Rcpp/commit/4f0e964f6daaeb4e201d0fdec6cef702600be4f5#diff-e77ce31ae6ab92649ef2a4976d6b1485R100

**Comment by hadley** [comment] 2018-06-06 22:06
🤣 I'll file an issue!

(Although in this case this problem will be resolved once conflicted knows about derived S4 generics)

**Comment by hpages** [comment] 2018-06-06 22:29
I believe that chances of unintended conflicts **within** Bioconductor is indeed lower thanks to greater centralization and coordination. In that regard BiocGenerics has been a key component in reducing the chances of unintended conflicts.

The most unintended conflicts we see those days are between Bioconductor and tidyverse as more and more typical Bioconductor workflows are starting to make use of tidyverse tools, especially towards the end of the analysis pipe. So yes, anything that can improve the interaction between Bioconductor and tidyverse is welcome. In that regard conflicted will be a great addition. Once it's mature enough, we will probably add it to the `Depends` field of BiocGenerics.

BTW let us know when you think conflicted is ready for a crash test against Bioconductor. It will be easy (and fun) for us to add it to BiocGenerics `Depends` field in devel and watch the world collapse one day after here (after a full build cycle): https://bioconductor.org/checkResults/3.8/bioc-LATEST/  :wink: The diff between the new build report and the report from the day before will give us useful feedback.

**Comment by hadley** [comment] 2018-07-24 18:46
Closing in favour of #2.  In the future, conflicted will assume that any function that clashes with a base function follows the superset principle, unless it has a special attribute set (which we'll add to `dplyr::filter()` and `dplyr::lag()`).

**Closed** 2018-07-24 18:48 UTC

**Comment by hadley** [comment] 2018-08-22 21:13
This is now implemented:

```
> conflicts_find(c("BiocGenerics", base_packages))
72 conflicts
* `anyDuplicated`: [BiocGenerics]
* `append`       : [BiocGenerics]
* `as.data.frame`: [BiocGenerics]
* `as.list`      : [BiocGenerics]
* `boxplot`      : [BiocGenerics]
* `cbind`        : [BiocGenerics]
* `colMeans`     : [BiocGenerics]
* `colnames`     : [BiocGenerics]
* `colnames<-`   : [BiocGenerics]
* `colSums`      : [BiocGenerics]
* `density`      : [BiocGenerics]
* `do.call`      : [BiocGenerics]
* `duplicated`   : [BiocGenerics]
* `end`          : [BiocGenerics]
* `eval`         : [BiocGenerics]
* `evalq`        : [BiocGenerics]
* `Filter`       : [BiocGenerics]
* `Find`         : [BiocGenerics]
* `get`          : [BiocGenerics]
* `grep`         : [BiocGenerics]
* `grepl`        : [BiocGenerics]
* `image`        : [BiocGenerics]
* `intersect`    : [BiocGenerics]
* `IQR`          : [BiocGenerics]
* `is.unsorted`  : [BiocGenerics]
* `lapply`       : [BiocGenerics]
* `lengths`      : [BiocGenerics]
* `mad`          : [BiocGenerics]
* `Map`          : [BiocGenerics]
* `mapply`       : [BiocGenerics]
* `match`        : [BiocGenerics]
* `mean`         : [BiocGenerics]
* `mget`         : [BiocGenerics]
* `ncol`         : [BiocGenerics]
* `NCOL`         : [BiocGenerics]
* `nrow`         : [BiocGenerics]
* `NROW`         : [BiocGenerics]
* `order`        : [BiocGenerics]
* `paste`        : [BiocGenerics]
* `pmax`         : [BiocGenerics]
* `pmax.int`     : [BiocGenerics]
* `pmin`         : [BiocGenerics]
* `pmin.int`     : [BiocGenerics]
* `Position`     : [BiocGenerics]
* `rank`         : [BiocGenerics]
* `rbind`        : [BiocGenerics]
* `Reduce`       : [BiocGenerics]
* `relist`       : [BiocGenerics]
* `rep.int`      : [BiocGenerics]
* `residuals`    : [BiocGenerics]
* `rowMeans`     : [BiocGenerics]
* `rownames`     : [BiocGenerics]
* `rownames<-`   : [BiocGenerics]
* `rowSums`      : [BiocGenerics]
* `sapply`       : [BiocGenerics]
* `sd`           : [BiocGenerics]
* `setdiff`      : [BiocGenerics]
* `sort`         : [BiocGenerics]
* `start`        : [BiocGenerics]
* `subset`       : [BiocGenerics]
* `t`            : [BiocGenerics]
* `table`        : [BiocGenerics]
* `tapply`       : [BiocGenerics]
* `union`        : [BiocGenerics]
* `unique`       : [BiocGenerics]
* `unsplit`      : [BiocGenerics]
* `var`          : [BiocGenerics]
* `weights`      : [BiocGenerics]
* `which`        : [BiocGenerics]
* `which.max`    : [BiocGenerics]
* `which.min`    : [BiocGenerics]
* `xtabs`        : [BiocGenerics]
```

(listing a single package means that the conflict has been resolved in the favour of that package by some rule, in this case the superset principle).

I've manually flagged `dplyr::filter()` and `dplyr::lag()` as violators of this rule, so they do generic conflicts:

```R
> conflicts_find(c("dplyr", base_packages))
6 conflicts
* `filter`   : dplyr, stats
* `intersect`: [dplyr]
* `lag`      : dplyr, stats
* `setdiff`  : [dplyr]
* `setequal` : [dplyr]
* `union`    : [dplyr]
```
